#ifndef _HIPPSIMD_VEC_H_
#define _HIPPSIMD_VEC_H_
#include "vecd4.h"
#include "vecs8.h"
#include "veci8_32.h"
#include "veci16_16.h"
#include "veci32_8.h"
#include "veci64_4.h"
#endif	//_HIPPSIMD_VEC_H_