#ifndef _HIPPNUMERICAL_GSL_UTIL_VECTOR_VIEW_H_
#define _HIPPNUMERICAL_GSL_UTIL_VECTOR_VIEW_H_
namespace HIPP::NUMERICAL {


} // namespace HIPP::NUMERICAL
#endif	//_HIPPNUMERICAL_GSL_UTIL_VECTOR_VIEW_H_