#include <h5_obj_raw_datatype.h>
namespace HIPP {
namespace IO {

#define _HIPPIO_H5_PRE_T(obj_name, h5_id) \
    extern const _H5Datatype obj_name {h5_id, 0};

_HIPPIO_H5_PRE_T(_NATIVE_CHAR_T, H5T_NATIVE_CHAR)
_HIPPIO_H5_PRE_T(_NATIVE_SCHAR_T, H5T_NATIVE_SCHAR)
_HIPPIO_H5_PRE_T(_NATIVE_SHORT_T, H5T_NATIVE_SHORT)
_HIPPIO_H5_PRE_T(_NATIVE_INT_T, H5T_NATIVE_INT)
_HIPPIO_H5_PRE_T(_NATIVE_LONG_T, H5T_NATIVE_LONG)
_HIPPIO_H5_PRE_T(_NATIVE_LLONG_T, H5T_NATIVE_LLONG)
_HIPPIO_H5_PRE_T(_NATIVE_UCHAR_T, H5T_NATIVE_UCHAR)
_HIPPIO_H5_PRE_T(_NATIVE_USHORT_T, H5T_NATIVE_USHORT)
_HIPPIO_H5_PRE_T(_NATIVE_UINT_T, H5T_NATIVE_UINT)
_HIPPIO_H5_PRE_T(_NATIVE_ULONG_T, H5T_NATIVE_ULONG)
_HIPPIO_H5_PRE_T(_NATIVE_ULLONG_T, H5T_NATIVE_ULLONG)
_HIPPIO_H5_PRE_T(_NATIVE_FLOAT_T, H5T_NATIVE_FLOAT)
_HIPPIO_H5_PRE_T(_NATIVE_DOUBLE_T, H5T_NATIVE_DOUBLE)

_HIPPIO_H5_PRE_T(_C_S1_T, H5T_C_S1)

_HIPPIO_H5_PRE_T(_STD_I8LE_T, H5T_STD_I8LE)
_HIPPIO_H5_PRE_T(_STD_I16LE_T, H5T_STD_I16LE)
_HIPPIO_H5_PRE_T(_STD_I32LE_T, H5T_STD_I32LE)
_HIPPIO_H5_PRE_T(_STD_I64LE_T, H5T_STD_I64LE)
_HIPPIO_H5_PRE_T(_STD_U8LE_T, H5T_STD_U8LE)
_HIPPIO_H5_PRE_T(_STD_U16LE_T, H5T_STD_U16LE)
_HIPPIO_H5_PRE_T(_STD_U32LE_T, H5T_STD_U32LE)
_HIPPIO_H5_PRE_T(_STD_U64LE_T, H5T_STD_U64LE)
_HIPPIO_H5_PRE_T(_IEEE_F32LE_T, H5T_IEEE_F32LE)
_HIPPIO_H5_PRE_T(_IEEE_F64LE_T, H5T_IEEE_F64LE)

_HIPPIO_H5_PRE_T(_STD_I8BE_T, H5T_STD_I8BE)
_HIPPIO_H5_PRE_T(_STD_I16BE_T, H5T_STD_I16BE)
_HIPPIO_H5_PRE_T(_STD_I32BE_T, H5T_STD_I32BE)
_HIPPIO_H5_PRE_T(_STD_I64BE_T, H5T_STD_I64BE)
_HIPPIO_H5_PRE_T(_STD_U8BE_T, H5T_STD_U8BE)
_HIPPIO_H5_PRE_T(_STD_U16BE_T, H5T_STD_U16BE)
_HIPPIO_H5_PRE_T(_STD_U32BE_T, H5T_STD_U32BE)
_HIPPIO_H5_PRE_T(_STD_U64BE_T, H5T_STD_U64BE)
_HIPPIO_H5_PRE_T(_IEEE_F32BE_T, H5T_IEEE_F32BE)
_HIPPIO_H5_PRE_T(_IEEE_F64BE_T, H5T_IEEE_F64BE)


#undef _HIPPIO_H5_PRE_T

} // namespace IO
} // namespace HIPP